"""Shared configuration for gbrain services."""
import os
from dataclasses import dataclass, field


def _require_pg_password() -> str:
    """Read PG_PASSWORD from env, fail loudly with a clear remediation hint.

    install.sh generates this at install time and writes it to both the .env
    and the systemd EnvironmentFile (/etc/gbrain/secrets.env). If you see this
    error, the most likely cause is that you bypassed install.sh or that the
    secrets file is missing — re-run install.sh, or inspect
    /etc/gbrain/secrets.env to confirm PG_PASSWORD is present.
    """
    pw = os.environ.get("PG_PASSWORD")
    if pw is None:
        raise RuntimeError(
            "PG_PASSWORD is not set. It is generated by scripts/install.sh and "
            "written to /etc/gbrain/secrets.env. Re-run install.sh or export "
            "PG_PASSWORD manually before starting services."
        )
    return pw


@dataclass(frozen=True)
class Config:
    """Service configuration loaded from environment variables."""

    pg_host: str = field(
        default_factory=lambda: os.environ.get("PG_HOST", "/var/run/postgresql")
    )
    pg_port: int = field(
        default_factory=lambda: int(os.environ.get("PG_PORT", "5432"))
    )
    pg_database: str = field(
        default_factory=lambda: os.environ.get("PG_DATABASE", "gbrain")
    )
    pg_user: str = field(
        default_factory=lambda: os.environ.get("PG_USER", "gbrain")
    )
    pg_password: str = field(
        default_factory=_require_pg_password
    )
    vault_root: str = field(
        default_factory=lambda: os.environ.get(
            "VAULT_ROOT", "/opt/gbrain/vault"
        )
    )
    fastembed_model: str = field(
        default_factory=lambda: os.environ.get(
            "FASTEMBED_MODEL", "intfloat/multilingual-e5-large"
        )
    )
    mcp_host: str = field(
        default_factory=lambda: os.environ.get("MCP_HOST", "0.0.0.0")
    )
    mcp_port: int = field(
        default_factory=lambda: int(os.environ["MCP_PORT"])
    )

    def get_pg_dsn(self) -> dict[str, str | int]:
        """Return asyncpg connection kwargs.

        Uses unix socket when pg_host starts with '/', TCP otherwise.
        """
        base: dict[str, str | int] = {
            "database": self.pg_database,
            "user": self.pg_user,
            "password": self.pg_password,
            "host": self.pg_host,
        }
        # Only include explicit port for TCP. Unix-socket hosts (paths starting
        # with '/') ignore port but asyncpg is happy either way.
        if not self.pg_host.startswith("/"):
            base["port"] = self.pg_port
        return base
